### ISSUE TITLE
Module and Inventory plugin instance value consistency

### ISSUE THREAD

**Issue by nleiva** [ServiceNowITOM/servicenow-ansible#17]
The ServiceNow Inventory Plugin `now` takes the full URI (FQDN) for the `instance` parameter (`SN_INSTANCE`). 

On the other hand, modules `snow_record` and `snow_record_find` use only the the prefix (without `.service-now.com`).

From the examples:

```yaml
plugin: servicenow.servicenow.now
instance: demo.service-now.com
username: admin
password: password
...
```

vs

```yaml
- name: Search for incident assigned to group, return specific fields
  snow_record_find:
    username: ansible_test
    password: my_password
    instance: dev99999
    ...
```

Would it be possible to make it look the same everywhere?
