### ISSUE TITLE
Inventory transforms '-' (dashes) in hostnames to '_' (underscores)

### ISSUE THREAD

**Issue by gforster** [ServiceNowITOM/servicenow-ansible#22]
not really sure why, but it is transforming all dashes in hostnames to underscores. 

Followd the handy guide here to get the plugin working in Tower - https://www.ansible.com/blog/using-an-inventory-plugin-from-a-collection-in-ansible-tower

as an aside, it would be handy to be able to do hostname transforms ourselves as our CMDB has everything in uppercase, but we otherwise use lowercase for everything else.

my servicenow.yml is pretty simple:
```
plugin: servicenow.servicenow.now
table: u_cmdb_ci_assets
fields: [u_network_ip_address,u_asset_name,u_application_owner,u_database_owner,name,u_os,u_service_tier,u_os_owner_team_name]
filter_results: 'u_os_owner_team_name=a7134318db1c87406431572e5e961946^install_status=1'
keyed_groups:
- key: sn_u_os | lower
  prefix: ''
  separator: ''
- key: sn_u_service_tier | lower
  prefix: ''
  separator: ''
```

But a hostname like `ABCD-DB-AB123` comes into Tower as `ABCD_DB_AB123`

**Comment by gforster** [comment]
I believe this has to do with line 271:
```
                host_name = self.inventory.add_host(to_safe_group_name(target))
```
Is there a reason that you're using `to_safe_group_name` with the `host_name`? Shouldn't this be done on the group level?

**Comment by wormley** [comment]
Looks like a bug to me too. We encountered the same problem. If it's wanted it should at least be configurable.

**Comment by willtome** [comment]
@gforster @wormley please test version `1.0.3-dev3` from galaxy.ansible.com and let me know if this resolves your issue.

**Comment by gforster** [comment]
@willtome I am still getting underscores instead of dashes in hostnames.

**Comment by gforster** [comment]
You can see the result here - interesting that it recognizes the dashes in the vars

![image](https://user-images.githubusercontent.com/3602462/94044483-338fa980-fd9c-11ea-81ff-322de562053e.png)

**Comment by willtome** [comment]
@gforster please ensure you are using version `1.0.3-dev3`. With the `dev3` suffix this release is not considered "latest". Here are some installation tips to make sure you are using the right version.

Install with Ansible Galaxy Command:
`ansible-galaxy collection install servicenow.servicenow:1.0.3-dev3`

Install with requirements.yml file:
```
---
collections:
  - name: servicenow.servicenow
    version: 1.0.3-dev3
```

Ansible Tower 3.7.0
Ansible 2.9.9

```
$ ansible-inventory -i now.yml --graph

@all:
  |--@ungrouped:
  |  |--AS400
  |  |--ApplicationServerHelpdesk
  |  |--ApplicationServerPeopleSoft
  |  |--Car-1
  |  |--Car-2
  |  |--Car-3
  |  |--Car-4
```

<img width="519" alt="image" src="https://user-images.githubusercontent.com/5437553/96289492-289ef200-0fb3-11eb-930a-4226c77ed484.png">
