### ISSUE TITLE
Need in helping grouping hosts based on filter condition

### ISSUE THREAD

**Issue by kumaresan078** [ServiceNowITOM/servicenow-ansible#46]
Hi Ansible Gurus

Could someone help me with below queries to achieve?

I need to filter servers from servicenow based on fields such as Operation status=Operational and Status=Installed ?

In addition need to group the hosts based on below condition?

Business Unit anything starts with string* and Business Unit anything except string* need to be different group

Also I need to filter hosts based on the IP address fields?

**Comment by epicanthal** [comment]
Hi,

I'm not a Guru, but possibly I can assist.  Are you referring to inventory?  If so, maybe this PR #44 I've submitted recently will help.  I've provide add'l documentation and an example in [docs/inventory.md](https://github.com/ServiceNowITOM/servicenow-ansible/pull/44/files) for using ```filter_results```

**Comment by kumaresan078** [comment]
Hi Epicanthal,

Thanks for information. I am trying filter like below to segerate hosts into groups from servicenow CMDB based different filters.

Can we have custom group name in keyed_groups?

There are fields in servicenow CMDB such IP address and Business unit need filter condition based on below query for the same.

Business Unit anything starts with string* and Business Unit anything except string* need to be different group

Also I need to filter hosts based on the IP address fields?

plugin: servicenow.servicenow.now
table: cmdb_ci_linux_server
selection_order: host_name
fields: [name,host_name,fqdn,ip_address,sys_class_name, install_status, classification,vendor, os, used_for, approval_group, ci_owner]
filter_results: install_status=1^ci_ownerSTARTSWITHazuresupport
keyed_groups:
  - key: sn_install_status | lower
    prefix: 'status'
filter_results: install_status=1^ci_ownerSTARTSWITHlinux
keyed_groups:
  - key: sn_install_status | lower
    prefix: 'status'

**Comment by kumaresan078** [comment]
Is it possible to use two groups with different filters?

key: sn_install_status | lower
prefix: 'status'
filter_results: install_status=1^ci_ownerSTARTSWITHlinux
keyed_groups:
key: sn_install_status | lower
filter_results: install_status=1^ci_ownerSTARTSWITHwindows
prefix: 'status'

**Comment by epicanthal** [comment]
This link might be useful:  [Inventory Plugins](https://docs.ansible.com/ansible/latest/plugins/inventory.html)

I think it will be helpful to know that the ```filter_results``` is just acting on the initial request to pull your data back from the CMDB.  Your ```filter_results: install_status=1^ci_ownerSTARTSWITHazuresupport``` as you may have already determined returns only the requested (filtered) records instead of the entire table.  This definitely helps performance for Ansible and of course less stress on you instance 👍 

The ```constructed``` inventory plugin is what allows for "keyed_groups" and a couple other useful parameters "groups" and "compose":  [ansible.builtin.constructed](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/constructed_inventory.html).  Notice that ```filter_results``` is not one of the parameters for the ```constructed``` plugin.  The reason is that ```filter_results``` is specific to the servicenow.servicenow.now plugin.  Similar to the "webservers" example provided there, you might be able to do something like:
```yaml
groups:
   owner_linux: sn_ci_owner.startswith('linux')
   owner_windows: sn_ci_owner.startswith('windows')
```
OR
Here's an example I was able to get working:
```yaml
keyed_groups:
  - key: sn_company | lower
    prefix: company
```
Which gave me groups like:
```
# ansible-inventory -i now.yml --graph | grep \@company
  |--@company:
  |--@company_acme:
  |--@company_acme-candy:
  |--@company_acme-cookies:
  |--@company_acme-coffee:
```

Believe me, I've struggled many hours trying to figure out some of this inventory stuff :)  I still don't have a good handle on it.

**Comment by kumaresan078** [comment]
Hi epicanthal,

Thanks for the update.How could i convert below filter_results into groups? Can't we use filter for each keyed_groups?

filter_results: install_status=1^support_groupSTARTSWITHwindows^u_business_unitNOT LIKEapps^ip_addressSTARTSWITH192.28

Does below format will work?

groups:
owner_windows:install_status=1^support_groupSTARTSWITHwindows^u_business_unitNOT LIKEapps^ip_addressSTARTSWITH192.28

**Comment by epicanthal** [comment]
You might be able to do what you want via commandline patterns:  https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html.  Maybe create keyed_groups for business_unit, apps, support_groups, etc. then use the info in the "patterns" link to combine at the commandline when calling ansible.

but maybe something like this will work if you want to continue to try with the inventory plugin:

```yaml
plugin: servicenow.servicenow.now
table: cmdb_ci_linux_server
selection_order: host_name
fields: [name,host_name,fqdn,ip_address,support_group,u_business_unit,sys_class_name, install_status, classification,vendor, os, used_for, approval_group, ci_owner]
filter_results: install_status=1
groups:
  owner_windows: sn_support_group.startswith('windows') and
                 sn_ip_address.startswith('192.28') and
                 sn_u_bussiness_unit | regex_search('(apps)')
```

Refer here for more info on that regex_search filter I used above:  https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#searching-strings-with-regular-expressions

I don't claim this will work, it's just something I might try if I were trying do it.  You definitely should try to iterate until you get results closer to what you want.  e.g. first just try ```owner_windows: sn_support_group.startswith('windows')``` to see if that gets you just the CIs where "support_group starts with windows".  Then add the next part with the ```and``.  I hope this helps.

Again, remember you cannot use ```filter_results``` within keyed_groups or groups, only the initial definition like in my example which filters the data you are pulling from the CMDB.  Grouping via the keyed_groups and groups sections is all processing after ansible has retrieved the data.
