### ISSUE TITLE
Inventory plugin: Solution for generating host_vars from multiple tables

### ISSUE THREAD

**Issue by jervislam0911** [ServiceNowITOM/servicenow-ansible#63]
Hi all.

I wonder is Inventory plugin able to target/join multiple tables from ServiceNow. As for now, it can only target one table at a time.
Rather than creating a view in ServiceNow. Is there any build-in method that can get fields from other tables by using this plugin ? 

**Expecting (using multiple tables):**
```
plugin: servicenow.servicenow.now
instance: my_instance
username: my_user
password: my_password
table: u_cmdb_ci_ssc_vmware_instance,cmdb_ci_server
fields:
  - environment
  - u_original_source
  - u_private_ip
  - u_host_type_used
  - fqdn
  - name
  - u_processor
  - u_cloud_env
  - u_no_of_processors
  - <field_from_another_table>
keyed_groups:
  - key: environment | lower
    prefix: 'env'
```
Thanks,
