### ISSUE TITLE
Comments and work notes not appearing for snow_record_find module

### ISSUE THREAD

**Issue by jangel97** [ServiceNowITOM/servicenow-ansible#65]
Hello everyone,

I am trying to use _servicenow-ansible_ collection to automate ticket management in SN. 
I want to retrieve the comments of resulting records after querying SN via snow_record_find module. In order to do so, this is how my ansible playbook looks:

```yaml
---
- name: play
  hosts: localhost
  gather_facts: no
  collections:
    - servicenow.servicenow
  vars_files:
    - vars.yml
  tasks:
  - name: Find open standard changes with my template
    snow_record_find:
      username: "{{ hv_sn_credentials.username }}"
      password: "{{ hv_sn_credentials.password }}"
      instance: "{{ sn_instance }}"
      table: "{{ table }}"
      query:
        task_effective_number: "{{ my_test_sn_task }}"
      return_fields:
        - comments
        - work_notes
        - sys_id
        - short_description
    register: result
  - debug: var=result
```
This is the result so far:
```json
    "result": {
        "changed": false,
        "failed": false,
        "record": [
            {
                "comments": "",
                "short_description": "test ansible servicenow collection ",
                "sys_id": "<sys_id>",
                "work_notes": ""
            }
        ]
    }
}
```
However, if I test against the SN api directly, using the following command: 
```curl
curl https://<sn_instance>/api/now/table/sys_journal_field?sysparm_query=element_id=<sys_id>^element=comments^ORDERBYDESCsys_created_on -u '<user>:<password>' --silent | python -m json.tool
```
As you can see there are indeed comments, so API can retrieve the comments:
```json
{
    "result": [
        {
            "element": "comments",
            "element_id": "<elem_id>",
            "name": "incident",
            "sys_created_by": "<user>",
            "sys_created_on": "2021-07-07 16:03:15",
            "sys_id": "<sys_id>",
            "sys_tags": "",
            "value": "more more comments"
        },
        {
            "element": "comments",
            "element_id": "<elem_id>",
            "name": "incident",
            "sys_created_by": "<user>",
            "sys_created_on": "2021-07-06 16:27:20",
            "sys_id": "<sys_id>",
            "sys_tags": "",
            "value": "change state"
        }
    ]
}
```
This is very much the same with work_notes. 

My question is, can I use the ansible module `snow_record_find` to retrieve the comments? Can I be missing something to achieve this behaviour?

Thanks in advance and kind regards,
