### ISSUE TITLE
Passing in a datetime for less_than, greater_than

### ISSUE THREAD

**Issue by lotaris-xx** [ServiceNowITOM/servicenow-ansible#66]
When doing a query I am trying to do something like:

```
set_fact:
   avar: "2021-10-01 01:00:00"

less_than:
    some_snow_datetime_field: "{{ avar }}"
```

And getting and error back from pysnow that this needs to be a datetime or int (although the pysnow docs say a str should work).

So I tried:

```
less_than:
   some_snow_datetime_field: "{{ avar | to_datetime }}"
```
but  I think ansible is helping me here and converting the datetime object back to a string?

Any chance of getting this working?
