### ISSUE TITLE
Error on create or update

### ISSUE THREAD

**Issue by bartheerman** [ServiceNowITOM/servicenow-ansible#68]
I want to create or update a record. To do this, I use this code:
```yaml
    - name: Update or create a record
      servicenow.servicenow.snow_record:
        username: xxx
        password: yyy
        instance: zzz
        state: present
        table: cmdb_ci
        lookup_field: name
        number: MyTestDevice
        data:
          name: "MyTestDevice"
          serial: "aaaa"
```
When the entry is not yet present in the cmdb_ci table, the module exits with the error:
```fatal: [localhost]: FAILED! => {"changed": false, "msg": "Record does not exist"}```

Looking at the code, there is no create when providing ```number``` and ```state: present```.
