### ISSUE TITLE
How to pass variables to servicenow.yml?

### ISSUE THREAD

**Issue by nsandhu-godaddy** [ServiceNowITOM/servicenow-ansible#74]
Hi,

I was able to get this to work following the instructions [here](https://www.ansible.com/blog/using-an-inventory-plugin-from-a-collection-in-ansible-tower).

However, I was wondering if there was a way to pass variables into serivcenow.yml file. I would like to set the `filter_results` field to a variable, something like this:

```
lugin: servicenow.servicenow.now
table: cmdb_ci_linux_server
selection_order: name
fields: [ip_address,fqdn,name,location.name,u_cmdb_ci_service.name]
filter_results: "{{ servicenow_filter_results | default('install_status=1^nameCONTAINSstuff') }}"
keyed_groups:
  - key: location.name | lower
    prefix: ''
    separator: ''
  - key: u_cmdb_ci_service.name | lower
    prefix: ''
    separator: ''

```

In AWX, I configured the Inventory Source to have a Source variable `servicenow_filter_results` set to a different filter criteria.
