### ISSUE TITLE
Preferred way to query and filter elements within cmdb_rel_ci

### ISSUE THREAD

**Issue by HSchmale16** [ServiceNowITOM/servicenow-ansible#77]
I'm trying to find a mapped application service and walk to it using this module.  To do that I query one cmdb table, and use the sys_ids to walk there.

However I need to filter by the child.class field to find the actual things. I can see it in the table elements within the ui, but I can't seem to pass that value in. 

What would querying by one of these derived attributes look like? So far I've tried just adding a field called `child.class` to my query.

From the examples my query looks like:

```
- name: Search for incident using host instead of instance
  servicenow.servicenow.snow_record_find:
    username: ansible_test
    password: my_password
    host: dev99999.mycustom.domain.com
    table: cmdb_rel_ci
    query:
      parent: <some_sys_id>
      child.class: <another_sys_id>
   ```

However `child.class` is ignored in my query, and it returns all the records for the given parent.

Any recommendations on how to proceed would be much appreciated.
