### ISSUE TITLE
Docs on https://docs.ansible.com/ansible/6/collections/servicenow/servicenow/snow_record_module.html need updating

### ISSUE THREAD

**Issue by ffirg** [ServiceNowITOM/servicenow-ansible#79]
The example data payload under https://docs.ansible.com/ansible/6/collections/servicenow/servicenow/snow_record_module.html#examples refers to 
```
- name: Create an incident
  servicenow.servicenow.snow_record:
    username: ansible_test
    password: my_password
    instance: dev99999
    state: present
    data:
      short_description: "This is a test incident opened by Ansible"
      severity: 3
      priority: 2
  register: new_incident
```

But when using with the latest SNOW Washington release, in order to update an incident properly you should pass impact and urgency and then SNOW will set the priority. This is an example snippet that works:
```
data:
          short_description: Event Driven Ansible Remediation Incident
          impact: 2
          urgency: 1
```

Trying to use the existing doc example does not have the desired effect in tersm of priority etc
